# Generated by Django 5.2.3 on 2025-06-20 10:24

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups_to_create = [
        # Руководство и Администрация
        'IT-Администраторы',
        'Главный врач',
        'Администрация центра',
        'Финансовый отдел / Бухгалтерия',
        'Отдел кадров (HR)',
        # Клинический персонал
        'Лечащие врачи',
        'Врачи-специалисты',
        'Старшая медсестра',
        'Медсестры',
        'Физиотерапевты',
        'Эрготерапевты',
        'Логопеды',
        'Психологи и психотерапевты',
        'Диетологи',
        # Диагностика и поддержка
        'Лаборанты',
        'Специалисты по диагностике (УЗИ, МРТ)',
        'Фармацевты',
        # Вспомогательный персонал
        'Регистратура',
        'Сотрудники архива / Мед. статистики',
        'Социальные работники',
    ]

    for group_name in groups_to_create:
        Group.objects.get_or_create(name=group_name)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_integrationsettings_systemsettings_auditlog'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
