# Generated by Django 5.2.3 on 2025-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
