# Generated by Django 5.2.3 on 2025-06-24 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_specialization_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('examination', 'Осмотр'), ('diagnosis', 'Диагноз'), ('treatment', 'Лечение'), ('procedure', 'Процедура'), ('prescription', 'Назначение'), ('note', 'Заметка'), ('other', 'Другое')], default='note', max_length=20, verbose_name='Тип записи')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная запись')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_medical_records', to='core.patient', verbose_name='Пациент')),
                ('related_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_medical_records', to='core.patientadmission', verbose_name='Связанная госпитализация')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
