# Generated by Django 5.2.3 on 2025-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Интеграция с 1С:Медицина', max_length=100, verbose_name='Название')),
                ('api_url', models.URLField(max_length=255, verbose_name='URL API 1С')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль/Токен доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Интеграция с 1С',
                'verbose_name_plural': 'Интеграции с 1С',
            },
        ),
    ]
