# Generated by Django 5.2.3 on 2025-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_integration1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration1c',
            name='last_sync_details',
            field=models.TextField(blank=True, verbose_name='Детали последней синхронизации'),
        ),
        migrations.AddField(
            model_name='integration1c',
            name='last_sync_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус последней синхронизации'),
        ),
        migrations.AddField(
            model_name='integration1c',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней синхронизации'),
        ),
    ]
