# Generated by Django 5.2.3 on 2025-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_integration1c_last_sync_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Интеграция с Zoom', max_length=255, verbose_name='Название интеграции')),
                ('account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account ID')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активировать интеграцию')),
            ],
            options={
                'verbose_name': 'Интеграция с Zoom',
                'verbose_name_plural': 'Интеграции с Zoom',
            },
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='api_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL API 1С'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активировать интеграцию'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='last_sync_details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали последней синхронизации'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='last_sync_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус последней синхронизации'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='name',
            field=models.CharField(default='Интеграция с 1С:Медицина', max_length=255, verbose_name='Название интеграции'),
        ),
        migrations.AlterField(
            model_name='integration1c',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
