# Generated by Django 5.2.3 on 2025-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_zoomintegration_alter_integration1c_api_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(choices=[('EGISZ', 'ЕГИСЗ'), ('GIS_OMS', 'ГИС ОМС'), ('ESIA', 'ЕСИА (Госуслуги)'), ('FGIS', 'ФГИС'), ('FSS', 'ФСС'), ('ERN', 'ЕРН (Вакцинированные)'), ('REMD', 'РЭМД (Электронные мед. документы)'), ('MDLP', 'Мониторинг лекарств (МДЛП)')], max_length=50, unique=True, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('api_url', models.URLField(blank=True, max_length=500, verbose_name='URL API')),
                ('login', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Пароль/Ключ API')),
                ('certificate_path', models.CharField(blank=True, help_text='Полный путь к файлу сертификата на сервере', max_length=500, verbose_name='Путь к сертификату ЭЦП')),
                ('private_key_path', models.CharField(blank=True, help_text='Полный путь к файлу приватного ключа на сервере', max_length=500, verbose_name='Путь к приватному ключу')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('extra_settings', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные параметры (JSON)')),
            ],
            options={
                'verbose_name': 'Интеграция с государственной системой',
                'verbose_name_plural': 'Интеграции с государственными системами',
                'ordering': ['system_name'],
            },
        ),
    ]
