# Generated by Django 5.2.3 on 2025-06-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_governmentintegration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovernmentIntegration',
        ),
    ]
