# Generated by Django 5.2.3 on 2025-06-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appointment_externalcalendarsync_notification_and_more'),
    ]

    operations = [
    ]
