# Generated by Django 5.2.3 on 2025-06-28 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_migration_conflict'),
        ('services', '0002_serviceappointment_is_telemedicine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Пропускаем создание уже существующих таблиц
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='appointment',
                    options={'ordering': ['-start_datetime'], 'verbose_name': 'Прием', 'verbose_name_plural': 'Приемы'},
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='all_day',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='appointment_type',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='color',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='reminder_datetime',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='reminder_sent',
                ),
                migrations.RemoveField(
                    model_name='appointment',
                    name='title',
                ),
                migrations.AddField(
                    model_name='appointment',
                    name='is_active',
                    field=models.BooleanField(default=True, verbose_name='Активен'),
                ),
                migrations.AddField(
                    model_name='appointment',
                    name='notes',
                    field=models.TextField(blank=True, verbose_name='Примечания'),
                ),
                migrations.AddField(
                    model_name='appointment',
                    name='price',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='appointment',
                    name='service',
                    field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Услуга'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='doctor',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='end_datetime',
                    field=models.DateTimeField(verbose_name='Конец'),
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='start_datetime',
                    field=models.DateTimeField(verbose_name='Начало'),
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='status',
                    field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
                ),
                migrations.AlterField(
                    model_name='appointment',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
                ),
            ],
            # Не выполняем никаких операций с базой данных
            database_operations=[],
        ),
        # Пропускаем создание моделей, которые уже существуют
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PatientDocument',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('insurance', 'Страховой полис'), ('medical', 'Медицинские документы'), ('other', 'Прочие документы')], max_length=20, verbose_name='Тип документа')),
                        ('file', models.FileField(upload_to='patient_documents/', verbose_name='Файл')),
                        ('description', models.TextField(blank=True, verbose_name='Описание')),
                        ('upload_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient', verbose_name='Пациент')),
                    ],
                    options={
                        'verbose_name': 'Документ пациента',
                        'verbose_name_plural': 'Документы пациентов',
                        'ordering': ['-upload_date'],
                    },
                ),
                migrations.CreateModel(
                    name='OptimizedServiceItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField()),
                        ('service_type', models.CharField(max_length=20)),
                        ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicecategory')),
                    ],
                    options={
                        'indexes': [models.Index(fields=['category'], name='core_optimi_categor_96f22c_idx'), models.Index(fields=['is_active'], name='core_optimi_is_acti_c0e6fa_idx'), models.Index(fields=['service_type'], name='core_optimi_service_ccb440_idx')],
                    },
                ),
            ],
            # Не выполняем никаких операций с базой данных
            database_operations=[],
        ),
        # Все операции перенесены в SeparateDatabaseAndState
    ]
