# Generated by Django 5.2.3 on 2025-06-19 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название назначения')),
                ('item_type', models.CharField(choices=[('medication', 'Лекарственный препарат'), ('procedure', 'Процедура'), ('recommendation', 'Рекомендация'), ('other', 'Другое')], default='medication', max_length=20, verbose_name='Тип назначения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Элемент справочника назначений',
                'verbose_name_plural': 'Справочник назначений',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='title',
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.treatmentitem', verbose_name='Назначение из справочника'),
        ),
    ]
