# Generated by Django 5.2.3 on 2025-06-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_populate_treatments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория назначений',
                'verbose_name_plural': 'Категории назначений',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='treatmentitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Элемент назначений (Справочник)', 'verbose_name_plural': 'Элементы назначений (Справочник)'},
        ),
        migrations.RemoveField(
            model_name='treatmentitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatmentitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='treatmentitem',
            name='item_type',
        ),

        migrations.AlterField(
            model_name='treatmentitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='treatmentitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.treatmentcategory', verbose_name='Категория'),
        ),
    ]
