# Generated by Django 5.2.3 on 2025-06-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_populate_treatment_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
