# Generated by Django 5.2.3 on 2025-06-26 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_treatmentitem_description'),
        ('medical_codes', '0002_icfcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordentry',
            name='is_sent_to_remd',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отправлено в РЭМД'),
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('final', 'Финал'), ('cancelled', 'Аннулирован')], default='draft', help_text='Статус документа: черновик, финал, аннулирован', max_length=10, verbose_name='Статус записи'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['status'], name='emr_medical_status_0f20ec_idx'),
        ),
    ]
