# Generated by Django 5.2.3 on 2025-06-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_medicalrecordentry_is_sent_to_remd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordentry',
            name='is_sent_to_remd',
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='remd_error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка РЭМД'),
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='remd_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сообщения РЭМД'),
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='remd_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('error', 'Ошибка отправки'), ('not_required', 'Не требует отправки')], db_index=True, default='not_required', max_length=20, verbose_name='Статус отправки в РЭМД'),
        ),
        migrations.CreateModel(
            name='RemdIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Данные ответа')),
                ('record_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remd_logs', to='emr.medicalrecordentry', verbose_name='Запись медкарты')),
            ],
            options={
                'verbose_name': 'Лог интеграции с РЭМД',
                'verbose_name_plural': 'Логи интеграции с РЭМД',
                'ordering': ['-timestamp'],
            },
        ),
    ]
