# Generated by Django 5.2.3 on 2025-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_remove_medicalrecordentry_is_sent_to_remd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remdintegrationlog',
            name='record_entry',
        ),
        migrations.RemoveIndex(
            model_name='medicalrecordentry',
            name='emr_medical_status_0f20ec_idx',
        ),
        migrations.RemoveField(
            model_name='medicalrecordentry',
            name='remd_error_message',
        ),
        migrations.RemoveField(
            model_name='medicalrecordentry',
            name='remd_message_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecordentry',
            name='status',
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='remd_document_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID документа в РЭМД'),
        ),
        migrations.AlterField(
            model_name='medicalrecordentry',
            name='remd_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'В обработке'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=10, verbose_name='Статус в РЭМД'),
        ),
        migrations.DeleteModel(
            name='RemdIntegrationLog',
        ),
    ]
