# Generated by Django 5.2.3 on 2025-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='is_telemedicine',
            field=models.BooleanField(default=False, verbose_name='Телемедицинская консультация'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL для подключения (пациент)'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID встречи Zoom'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL для начала встречи (врач)'),
        ),
    ]
