# Generated by Django 5.2.3 on 2025-06-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование организации')),
                ('clinic_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес организации')),
                ('clinic_ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Номер карты')),
                ('card_date', models.DateField(auto_now_add=True, verbose_name='Дата составления карты')),
                ('service_recipient_status', models.CharField(blank=True, choices=[('invalid', 'Инвалид'), ('child_invalid', 'Ребенок-инвалид'), ('other', 'Иное')], max_length=20, verbose_name='Статус получателя услуг')),
                ('course_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала реабилитационного курса')),
                ('service_contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора на услуги')),
                ('service_contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора на услуги')),
                ('disability_group', models.CharField(blank=True, choices=[('1', 'I группа'), ('2', 'II группа'), ('3', 'III группа'), ('child', 'Ребенок-инвалид'), ('none', 'Нет')], max_length=10, verbose_name='Группа инвалидности')),
                ('ipra_number', models.CharField(blank=True, max_length=100, verbose_name='Номер ИПРА')),
                ('ipra_date', models.DateField(blank=True, null=True, verbose_name='Дата ИПРА')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation_card', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Реабилитационная карта',
                'verbose_name_plural': 'Реабилитационные карты',
                'ordering': ['-card_date'],
            },
        ),
    ]
