# Generated by Django 5.2.3 on 2025-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehabilitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitationcard',
            name='activity_limitations',
            field=models.TextField(blank=True, help_text='Опишите ограничения в выполнении повседневных задач.', verbose_name='Ограничения активности (по МКФ)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='complications',
            field=models.TextField(blank=True, verbose_name='Осложнения основного заболевания'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='concomitant_diagnosis',
            field=models.TextField(blank=True, verbose_name='Сопутствующий диагноз'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='environmental_factors',
            field=models.TextField(blank=True, help_text='Опишите факторы окружающей среды, влияющие на пациента.', verbose_name='Факторы среды (по МКФ)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='long_term_goal',
            field=models.TextField(blank=True, verbose_name='Долгосрочная цель реабилитации'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='participation_restrictions',
            field=models.TextField(blank=True, help_text='Опишите ограничения в участии в социальных ситуациях.', verbose_name='Ограничения участия (по МКФ)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='primary_diagnosis',
            field=models.TextField(blank=True, verbose_name='Основной диагноз'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='primary_diagnosis_icd10',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код по МКБ-10'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='rehab_plan',
            field=models.TextField(blank=True, help_text='Опишите запланированные мероприятия, их периодичность и ответственных.', verbose_name='Индивидуальный план медицинской реабилитации'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='rehab_team',
            field=models.TextField(blank=True, help_text='Перечислите специалистов, участвующих в реабилитации.', verbose_name='Состав мультидисциплинарной реабилитационной команды'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='short_term_goals',
            field=models.TextField(blank=True, verbose_name='Краткосрочные цели (задачи)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='structural_impairments',
            field=models.TextField(blank=True, help_text='Опишите нарушения структур и функций организма.', verbose_name='Нарушения структуры и функций (по МКФ)'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rehabilitationcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
