# Generated by Django 5.2.3 on 2025-06-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0001_initial'),
        ('rehabilitation', '0002_rehabilitationcard_activity_limitations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitationcard',
            name='primary_diagnosis_icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_codes.icd10code', verbose_name='Код по МКБ-10'),
        ),
    ]
