# Generated by Django 5.2.3 on 2025-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0002_icfcode'),
        ('rehabilitation', '0003_alter_rehabilitationcard_primary_diagnosis_icd10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilitationcard',
            name='activity_limitations',
        ),
        migrations.RemoveField(
            model_name='rehabilitationcard',
            name='participation_restrictions',
        ),
        migrations.RemoveField(
            model_name='rehabilitationcard',
            name='structural_impairments',
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='rehab_diagnosis_b',
            field=models.ManyToManyField(blank=True, help_text='Выберите коды, описывающие нарушения функций организма.', limit_choices_to={'code__startswith': 'b'}, related_name='rehab_cards_b', to='medical_codes.icfcode', verbose_name='Нарушения функций (домен b)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='rehab_diagnosis_d',
            field=models.ManyToManyField(blank=True, help_text='Выберите коды, описывающие ограничения активности и участия.', limit_choices_to={'code__startswith': 'd'}, related_name='rehab_cards_d', to='medical_codes.icfcode', verbose_name='Активность и участие (домен d)'),
        ),
        migrations.AddField(
            model_name='rehabilitationcard',
            name='rehab_diagnosis_s',
            field=models.ManyToManyField(blank=True, help_text='Выберите коды, описывающие нарушения структур организма.', limit_choices_to={'code__startswith': 's'}, related_name='rehab_cards_s', to='medical_codes.icfcode', verbose_name='Нарушения структур (домен s)'),
        ),
    ]
