# Generated by Django 5.2.3 on 2025-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehabilitation', '0004_remove_rehabilitationcard_activity_limitations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitationcard',
            name='clinic_ogrn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОГРН'),
        ),
    ]
