# Generated by Django 5.2.3 on 2025-06-20 10:42

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_specializations'),
        ('documents', '0006_add_document_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('approve_document', 'Может утверждать документ')], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория документа', 'verbose_name_plural': 'Категории документов'},
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='template_content',
            field=models.TextField(blank=True, help_text='HTML-шаблон с плейсхолдерами для генерации документов.', null=True, verbose_name='Шаблон документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AlterField(
            model_name='document',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Утвержден кем'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.get_document_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_documents', to='core.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'Ожидает утверждения'), ('approved', 'Утвержден'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загружен кем'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient', verbose_name='Пациент'),
        ),
    ]
