# Generated by Django 5.2.3 on 2025-06-20 10:42

from django.db import migrations


CONTRACT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'Times New Roman', serif; font-size: 12pt; margin: 2cm; }
        .header { text-align: center; font-weight: bold; margin-bottom: 20px; }
        .section-title { font-weight: bold; margin-top: 15px; }
        .signatures { margin-top: 40px; }
        .signatures table { width: 100%; }
    </style>
</head>
<body>
    <div class="header">
        ДОГОВОР № {{ contract_number }}<br>
        на оказание платных медицинских услуг
    </div>
    <p>г. {{ city }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; «{{ day }}» {{ month }} {{ year }} г.</p>
    <p>
        {{ clinic_full_name }}, именуемое в дальнейшем «Исполнитель», в лице {{ director_full_name }}, действующего на основании Устава, с одной стороны, и
        гражданин(ка) <strong>{{ patient_full_name }}</strong>, именуемый(ая) в дальнейшем «Пациент», с другой стороны, заключили настоящий Договор о нижеследующем:
    </p>
    <div class="section-title">1. ПРЕДМЕТ ДОГОВОРА</div>
    <p>1.1. Исполнитель обязуется оказать Пациенту платные медицинские услуги в соответствии с перечнем и стоимостью, а Пациент обязуется оплатить эти услуги.</p>
    
    <div class="section-title">2. ПРАВА И ОБЯЗАННОСТИ СТОРОН</div>
    <p>2.1. Исполнитель обязан: ...</p>
    <p>2.2. Пациент обязан: ...</p>

    <div class="section-title">3. СТОИМОСТЬ УСЛУГ И ПОРЯДОК РАСЧЕТОВ</div>
    <p>3.1. Стоимость услуг определяется в соответствии с действующим Прейскурантом Исполнителя.</p>

    <div class="signatures">
        <table>
            <tr>
                <td><strong>Исполнитель:</strong></td>
                <td><strong>Пациент:</strong></td>
            </tr>
            <tr>
                <td>{{ clinic_details }}</td>
                <td>ФИО: {{ patient_full_name }}<br>Паспорт: {{ patient_passport_series }} {{ patient_passport_number }}<br>Адрес: {{ patient_address }}</td>
            </tr>
            <tr>
                <td><br>___________________ ({{ director_short_name }})</td>
                <td><br>___________________ ({{ patient_short_name }})</td>
            </tr>
        </table>
    </div>
</body>
</html>
"""

CONSENT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'Times New Roman', serif; font-size: 12pt; margin: 2cm; }
        .header { text-align: center; font-weight: bold; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        ИНФОРМИРОВАННОЕ ДОБРОВОЛЬНОЕ СОГЛАСИЕ<br>
        на виды медицинских вмешательств, включенные в Перечень...
    </div>
    <p>
        Я, <strong>{{ patient_full_name }}</strong>, {{ patient_birth_date }} года рождения, зарегистрированный по адресу: {{ patient_address }},
        даю информированное добровольное согласие на виды медицинских вмешательств, включенные в Перечень...
    </p>
    <p>
        Медицинским работником {{ doctor_full_name }} в доступной для меня форме мне разъяснены цели, методы оказания медицинской помощи, связанный с ними риск, возможные варианты медицинских вмешательств, их последствия, в том числе вероятность развития осложнений, а также предполагаемые результаты оказания медицинской помощи.
    </p>
    <p>
        Мне разъяснено, что я имею право отказаться от одного или нескольких видов медицинских вмешательств или потребовать его (их) прекращения...
    </p>
    <br><br>
    <p>Пациент: ___________________ / {{ patient_full_name }} /</p>
    <p>Дата: «{{ day }}» {{ month }} {{ year }} г.</p>
    <br>
    <p>Медицинский работник: ___________________ / {{ doctor_full_name }} /</p>
    <p>Дата: «{{ day }}» {{ month }} {{ year }} г.</p>
</body>
</html>
"""

PERSONAL_DATA_CONSENT_TEMPLATE = """
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Согласие на обработку ПДн</title></head><body>
<div style="text-align: center; font-weight: bold;">СОГЛАСИЕ <br>на обработку персональных данных</div>
<p>Я, <strong>{{ patient_full_name }}</strong>, в соответствии с требованиями статьи 9 Федерального закона от 27.07.2006 г. № 152-ФЗ «О персональных данных», даю свое согласие {{ clinic_full_name }} (далее – Оператор) на обработку моих персональных данных, включающих: фамилию, имя, отчество, пол, дату рождения, адрес проживания, контактный(е) телефон(ы), реквизиты полиса ОМС (ДМС), данные о состоянии моего здоровья, заболеваниях, случаях обращения за медицинской помощью, в медико-профилактических целях, в целях установления медицинского диагноза и оказания медицинских услуг.</p>
<p>Предоставляю Оператору право осуществлять все действия (операции) с моими персональными данными, включая сбор, систематизацию, накопление, хранение, обновление, изменение, использование, обезличивание, блокирование, уничтожение.</p>
<p>Срок хранения моих персональных данных соответствует сроку хранения первичных медицинских документов и составляет 25 лет.</p>
<p>Настоящее согласие действует бессрочно и может быть отозвано мной в письменной форме.</p>
<p>Дата: ___________________ Подпись: ___________________ ({{ patient_short_name }})</p>
</body></html>
"""

INITIAL_EXAM_TEMPLATE = """
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Первичный осмотр</title></head><body>
<h3 style="text-align: center;">ПЕРВИЧНЫЙ ОСМОТР ВРАЧА</h3>
<p><strong>Дата осмотра:</strong> {{ exam_date }}</p>
<p><strong>Пациент:</strong> {{ patient_full_name }}, {{ patient_birth_date }} г.р.</p>
<p><strong>Врач:</strong> {{ doctor_full_name }}</p>
<hr>
<p><strong>Жалобы:</strong></p><p>{{ complaints }}</p>
<p><strong>Анамнез заболевания (Anamnesis morbi):</strong></p><p>{{ anamnesis_morbi }}</p>
<p><strong>Анамнез жизни (Anamnesis vitae):</strong></p><p>{{ anamnesis_vitae }}</p>
<p><strong>Объективный статус (Status praesens):</strong></p><p>{{ status_praesens }}</p>
<p><strong>Предварительный диагноз:</strong></p><p>{{ preliminary_diagnosis }}</p>
<p><strong>План обследования:</strong></p><p>{{ examination_plan }}</p>
<p><strong>План лечения:</strong></p><p>{{ treatment_plan }}</p>
<br><br>
<p>Врач: ___________________ / {{ doctor_short_name }} /</p>
</body></html>
"""

DISCHARGE_SUMMARY_TEMPLATE = """
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Выписной эпикриз</title></head><body>
<h3 style="text-align: center;">ВЫПИСНОЙ ЭПИКРИЗ</h3>
<p>Пациент <strong>{{ patient_full_name }}</strong>, {{ patient_birth_date }} г.р., находился на стационарном лечении в {{ clinic_department }} с {{ admission_date }} по {{ discharge_date }}.</p>
<p><strong>Клинический диагноз:</strong></p><p>Основной: {{ primary_diagnosis }}</p><p>Сопутствующий: {{ concomitant_diagnosis }}</p>
<p><strong>Проведенное лечение и обследования:</strong></p><p>{{ treatment_and_examinations }}</p>
<p><strong>Состояние при выписке:</strong> {{ discharge_status }}</p>
<p><strong>Рекомендации:</strong></p><p>{{ recommendations }}</p>
<br><br>
<p>Лечащий врач: ___________________ / {{ doctor_short_name }} /</p>
<p>Зав. отделением: ___________________ / {{ head_of_department_short_name }} /</p>
</body></html>
"""

REFERRAL_TEMPLATE_057U = """
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Направление 057/у</title></head><body>
<div style="text-align: right;">Форма № 057/у-04</div>
<h3 style="text-align: center;">НАПРАВЛЕНИЕ</h3>
<h4 style="text-align: center;">на госпитализацию, обследование, консультацию</h4>
<p>Выдано: {{ patient_full_name }}</p>
<p>Дата рождения: {{ patient_birth_date }}</p>
<p>Адрес: {{ patient_address }}</p>
<p>Место работы: {{ patient_workplace }}</p>
<p>№ страхового полиса ОМС: {{ patient_oms_policy }}</p>
<p>Код льготы: {{ benefit_code }}</p>
<p>Диагноз: {{ diagnosis }}</p>
<p>Обоснование направления: {{ referral_reason }}</p>
<p>Направляется в: {{ destination_clinic }}</p>
<br><br>
<p>Лечащий врач: ___________________ / {{ doctor_short_name }} /</p>
<p>Зав. отделением: ___________________ / {{ head_of_department_short_name }} /</p>
</body></html>
"""

def populate_templates(apps, schema_editor):
    DocumentCategory = apps.get_model('documents', 'DocumentCategory')
    
    templates_data = {
        'Договор на оказание платных медицинских услуг': CONTRACT_TEMPLATE,
        'Информированное добровольное согласие': CONSENT_TEMPLATE,
        'Согласие на обработку персональных данных': PERSONAL_DATA_CONSENT_TEMPLATE,
        'Первичный осмотр врача': INITIAL_EXAM_TEMPLATE,
        'Выписной эпикриз': DISCHARGE_SUMMARY_TEMPLATE,
        'Направление на реабилитацию (форма 057/у)': REFERRAL_TEMPLATE_057U,
    }

    for name, template in templates_data.items():
        try:
            category = DocumentCategory.objects.get(name=name)
            category.template_content = template
            category.save()
        except DocumentCategory.DoesNotExist:
            print(f"Warning: DocumentCategory '{name}' not found. Skipping template population.")



class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_templates),
    ]
