# Generated by Django 5.2.3 on 2025-06-26 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsiaSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Включена ли эта интеграция?', verbose_name='Активна')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('api_url', models.URLField(max_length=500, verbose_name='URL API/сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client_id', models.CharField(max_length=255, verbose_name='ID клиента (мнемоника)')),
                ('client_secret', models.CharField(blank=True, max_length=1024, verbose_name='Секрет клиента')),
                ('redirect_uri', models.URLField(max_length=500, verbose_name='URI для перенаправления')),
                ('scope', models.CharField(default='openid profile email', max_length=1024, verbose_name='Запрашиваемые права (scope)')),
            ],
            options={
                'verbose_name': 'Настройка интеграции с ЕСИА',
                'verbose_name_plural': 'Настройки интеграции с ЕСИА',
            },
        ),
        migrations.CreateModel(
            name='FgisFssSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Включена ли эта интеграция?', verbose_name='Активна')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('api_url', models.URLField(max_length=500, verbose_name='URL API/сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('certificate_thumbprint', models.CharField(help_text='Используется для подписи запросов', max_length=255, verbose_name='Отпечаток сертификта ЭЦП')),
                ('fss_id', models.CharField(blank=True, max_length=50, verbose_name='Идентификатор страхователя в ФСС')),
            ],
            options={
                'verbose_name': 'Настройка интеграции с ФГИС ФСС',
                'verbose_name_plural': 'Настройки интеграции с ФГИС ФСС',
            },
        ),
        migrations.CreateModel(
            name='GisOmsSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Включена ли эта интеграция?', verbose_name='Активна')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('api_url', models.URLField(max_length=500, verbose_name='URL API/сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('wsdl_url', models.URLField(help_text='Адрес SOAP-сервиса для обмена данными', max_length=500, verbose_name='URL WSDL-сервиса')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, help_text='Пароль для аутентификации в сервисе', max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Настройка интеграции с ГИС ОМС',
                'verbose_name_plural': 'Настройки интеграции с ГИС ОМС',
            },
        ),
        migrations.CreateModel(
            name='RemdSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Включена ли эта интеграция?', verbose_name='Активна')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('api_url', models.URLField(max_length=500, verbose_name='URL API/сервиса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('org_oid', models.CharField(help_text='Уникальный идентификатор организации в РЭМД', max_length=255, verbose_name='OID медицинской организации')),
                ('auth_token', models.CharField(blank=True, help_text='Секретный ключ для доступа к API', max_length=1024, verbose_name='Токен авторизации')),
            ],
            options={
                'verbose_name': 'Настройка интеграции с РЭМД',
                'verbose_name_plural': 'Настройки интеграции с РЭМД',
            },
        ),
    ]
