# Generated by Django 5.2.3 on 2025-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_programs', '0004_alter_rehabactivity_options_rehabactivity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabactivity',
            name='category',
            field=models.CharField(choices=[('CONSULT_DIAGNOSTIC', 'Консультативно-диагностический блок'), ('LFK_KINESIO', 'Лечебная физкультура и кинезиотерапия'), ('PHYSIO_HARDWARE', 'Аппаратная физиотерапия'), ('MASSAGE_MANUAL', 'Массаж и мануальные техники'), ('PSYCHO_NEURO', 'Психокоррекция и нейропсихология'), ('SPEECH_DEFECTO', 'Логопедическая и дефектологическая помощь'), ('ERGO_SOCIAL', 'Эрготерапия и социально-бытовая адаптация'), ('HYDRO_THERAPY', 'Бальнео- и гидротерапия'), ('OTHER', 'Прочие процедуры')], default='OTHER', max_length=30, verbose_name='Категория'),
        ),
    ]
