# Generated by Django 5.2.3 on 2025-06-19 09:01

from django.db import migrations

ACTIVITIES_DATA = {
    'CONSULT_DIAGNOSTIC': [
        {'name': 'Первичная консультация врача-реабилитолога', 'duration': 60},
        {'name': 'Повторная консультация врача-реабилитолога', 'duration': 30},
        {'name': 'Консультация невролога', 'duration': 45},
        {'name': 'Консультация кардиолога с ЭКГ', 'duration': 45},
        {'name': 'Консультация травматолога-ортопеда', 'duration': 40},
        {'name': 'Консультация врача ЛФК', 'duration': 30},
        {'name': 'Консультация физиотерапевта', 'duration': 30},
        {'name': 'Спирометрия (оценка функции внешнего дыхания)', 'duration': 20},
        {'name': 'Электроэнцефалография (ЭЭГ)', 'duration': 30},
        {'name': 'Электронейромиография (ЭНМГ) стимуляционная, 1 нерв', 'duration': 30},
        {'name': 'УЗИ суставов (1 зона)', 'duration': 20},
        {'name': 'УЗДГ сосудов', 'duration': 30},
    ],
    'LFK_KINESIO': [
        {'name': 'Индивидуальное занятие ЛФК с инструктором', 'duration': 45},
        {'name': 'Групповое занятие ЛФК', 'duration': 60},
        {'name': 'Механотерапия на тренажере "Artromot"', 'duration': 30},
        {'name': 'Занятие на стабилометрической платформе с БОС', 'duration': 30},
        {'name': 'PNF-терапия (проприоцептивная нейромышечная фасилитация)', 'duration': 45},
        {'name': 'Бобат-терапия', 'duration': 50},
        {'name': 'Терапия на подвесных системах (Экзарта, Redcord)', 'duration': 45},
        {'name': 'Роботизированная механотерапия (Lokomat, Armeo)', 'duration': 60},
        {'name': 'Кинезиотейпирование (1 зона)', 'duration': 15},
        {'name': 'Дыхательная гимнастика (по Стрельниковой, Бутейко)', 'duration': 20},
        {'name': 'Тренировка ходьбы с протезом', 'duration': 45},
    ],
    'PHYSIO_HARDWARE': [
        {'name': 'Магнитотерапия (общая/локальная)', 'duration': 20},
        {'name': 'Лазеротерапия (включая ВЛОК)', 'duration': 15},
        {'name': 'Ультразвуковая терапия (фонофорез)', 'duration': 15},
        {'name': 'Электрофорез лекарственный', 'duration': 20},
        {'name': 'Амплипульстерапия (СМТ)', 'duration': 20},
        {'name': 'Диадинамотерапия (ДДТ)', 'duration': 15},
        {'name': 'Ударно-волновая терапия (УВТ)', 'duration': 20},
        {'name': 'Высокоинтенсивная импульсная магнитотерапия (SIS)', 'duration': 20},
        {'name': 'Прессотерапия (аппаратный лимфодренаж)', 'duration': 30},
        {'name': 'Криотерапия локальная', 'duration': 10},
        {'name': 'Общая баротерапия (гипербарическая оксигенация)', 'duration': 60},
        {'name': 'Зеркальная терапия (при фантомных болях)', 'duration': 30},
    ],
    'MASSAGE_MANUAL': [
        {'name': 'Медицинский массаж, 1.5 ед (15 мин)', 'duration': 15},
        {'name': 'Общий массаж (60 мин)', 'duration': 60},
        {'name': 'Лимфодренажный массаж ручной', 'duration': 40},
        {'name': 'Мануальная терапия', 'duration': 40},
        {'name': 'Остеопатическая коррекция', 'duration': 50},
        {'name': 'Иглорефлексотерапия', 'duration': 30},
    ],
    'PSYCHO_NEURO': [
        {'name': 'Нейропсихологическая диагностика', 'duration': 90},
        {'name': 'Индивидуальная нейропсихологическая коррекция', 'duration': 50},
        {'name': 'Консультация медицинского психолога (психодиагностика)', 'duration': 60},
        {'name': 'Индивидуальная психотерапия', 'duration': 50},
        {'name': 'Групповая психотерапия', 'duration': 90},
        {'name': 'Арт-терапия', 'duration': 60},
        {'name': 'Семейное психологическое консультирование', 'duration': 60},
        {'name': 'Когнитивно-поведенческая терапия (КПТ)', 'duration': 50},
    ],
    'SPEECH_DEFECTO': [
        {'name': 'Логопедическое занятие по восстановлению речи (афазия, дизартрия)', 'duration': 45},
        {'name': 'Логопедический массаж (зондовый, ручной)', 'duration': 30},
        {'name': 'Занятие по восстановлению функции глотания', 'duration': 30},
    ],
    'ERGO_SOCIAL': [
        {'name': 'Индивидуальное занятие с эрготерапевтом', 'duration': 45},
        {'name': 'Тренировка бытовых навыков (ADL)', 'duration': 60},
        {'name': 'Обучение пользованию ТСР (техническими средствами реабилитации)', 'duration': 40},
        {'name': 'Адаптация жилой среды (консультация)', 'duration': 60},
    ],
    'HYDRO_THERAPY': [
        {'name': 'Гидрокинезотерапия в бассейне (индивидуально)', 'duration': 40},
        {'name': 'Лечебные ванны (хвойные, солевые, жемчужные)', 'duration': 20},
        {'name': 'Подводный душ-массаж', 'duration': 30},
        {'name': 'Душ Шарко', 'duration': 15},
        {'name': 'Циркулярный душ', 'duration': 10},
    ],
    'OTHER': [
        {'name': 'Гирудотерапия (лечение пиявками)', 'duration': 40},
        {'name': 'Диетотерапия (разработка индивидуального меню)', 'duration': 40},
        {'name': 'Озонотерапия (внутривенно)', 'duration': 30},
    ],
}

def populate_rehab_activities(apps, schema_editor):
    RehabActivity = apps.get_model('rehab_programs', 'RehabActivity')
    db_alias = schema_editor.connection.alias

    for category, activities in ACTIVITIES_DATA.items():
        for activity_data in activities:
            RehabActivity.objects.using(db_alias).get_or_create(
                name=activity_data['name'],
                defaults={
                    'category': category,
                    'default_duration': activity_data['duration']
                }
            )

def unpopulate_rehab_activities(apps, schema_editor):
    RehabActivity = apps.get_model('rehab_programs', 'RehabActivity')
    db_alias = schema_editor.connection.alias
    
    activity_names = []
    for activities in ACTIVITIES_DATA.values():
        for activity_data in activities:
            activity_names.append(activity_data['name'])
            
    RehabActivity.objects.using(db_alias).filter(name__in=activity_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_programs', '0005_alter_rehabactivity_category'),
    ]

    operations = [
        migrations.RunPython(populate_rehab_activities, reverse_code=unpopulate_rehab_activities),
    ]
