# Generated by Django 5.2.3 on 2025-06-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_programs', '0008_populate_program_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitationprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
