# Generated by Django 5.2.3 on 2025-06-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0002_load_icd10_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10disease',
            name='is_category',
            field=models.BooleanField(default=False, verbose_name='Это категория?'),
        ),
        migrations.AddField(
            model_name='icd10disease',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medical_history.icd10disease', verbose_name='Родительская категория'),
        ),
    ]
