# Generated by Django 5.2.3 on 2025-06-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appointment_externalcalendarsync_notification_and_more'),
        ('medical_history', '0004_alter_medicalrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_medical_records', to='core.patient', verbose_name='Пациент'),
        ),
    ]
