# Generated by Django 5.2.3 on 2025-06-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICFCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_category', models.BooleanField(default=False, verbose_name='Это категория?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medical_codes.icfcode', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Код МКФ',
                'verbose_name_plural': 'Коды МКФ',
                'ordering': ['code'],
            },
        ),
    ]
